// this file is auto-generated by scripts/generate-racing-line-list.js

const entries = [
  {
    "name": "brazil_racing_lines.json",
    "absPath": "D:\\acrl\\AssettoCorsaRL-DOCS\\static\\json\\brazil_racing_lines.json",
    "publicUrl": "/json/brazil_racing_lines.json"
  },
  {
    "name": "monaco_racing_lines.json",
    "absPath": "D:\\acrl\\AssettoCorsaRL-DOCS\\static\\json\\monaco_racing_lines.json",
    "publicUrl": "/json/monaco_racing_lines.json"
  }
];

export default entries;
